<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryAbstractRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryAbstractRepository extends EntityRepository
{
    
    public function getGroupedCategories(){
        $groupedCategories = [];
        $groupedCategories['МПС - кубатура'] = 
                $this->createQueryBuilder('c')
                ->andWhere('c INSTANCE OF (:entity)')
                ->setParameter('entity', 'CarEngineCapacity')
                ->getQuery()->getResult();
        
        $groupedCategories['МПС - десен волан'] = 
                $this->createQueryBuilder('c')
                ->andWhere('c INSTANCE OF (:entity)')
                ->setParameter('entity', 'CarRightDirection')
                ->getQuery()->getResult();
        
        $groupedCategories['МПС - регистрационен номер'] = 
                $this->createQueryBuilder('c')
                ->andWhere('c INSTANCE OF (:entity)')
                ->setParameter('entity', 'CarRegistrationNumber')
                ->getQuery()->getResult();
        
        return $groupedCategories;
    }
    
    public function getTariffCategories(){
        
        return $this->createQueryBuilder('c')
                ->addSelect('c.category')
                ->groupBy('c.category')
                ->getQuery()
                ->getResult();
    }
    
    public function findCategoriesByIds(array $categoriesIds) {
        
        return $this->createQueryBuilder('c')
                ->andWhere('c IN (:categoriesIds)')
                ->setParameter('categoriesIds', $categoriesIds)
                ->getQuery()
                ->getResult();
        
    }
}
