<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use AppBundle\Entity\Calculator;
use AppBundle\Entity\BaseTariff; 
use AppBundle\Utils\InsuranceCalculator\InsuranceCalculator;
/**
 * ContractRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContractRepository extends EntityRepository
{  
}
