<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * InsurerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InsurerRepository extends EntityRepository
{
    public function getInsurersForUser(\Sonata\UserBundle\Model\User $user){
        
        $em = $this->getEntityManager();
        $qb = $this->createQueryBuilder('t');
        $entities = $qb
                ->andWhere('t.user = :user')
                ->setParameter('user', $user)
                ->getQuery()
                ->getResult();
        
        return $entities;
    }
    
}
