cms_carcategory_index:
    path:     /
    defaults: { _controller: "AppBundle:CMS\CarCategoryTariff:index" }
    methods:  GET

cms_carcategory_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:CMS\CarCategoryTariff:show" }
    methods:  GET

cms_carcategory_new:
    path:     /new
    defaults: { _controller: "AppBundle:CMS\CarCategoryTariff:new" }
    methods:  [GET, POST]

cms_carcategory_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:CMS\CarCategoryTariff:edit" }
    methods:  [GET, POST]

cms_carcategory_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:CMS\CarCategoryTariff:delete" }
    methods:  DELETE
