cms_categories_index:
    path:     /
    defaults: { _controller: "AppBundle:CategoryAbstract:index" }
    methods:  GET

cms_categories_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:CategoryAbstract:show" }
    methods:  GET

cms_categories_new:
    path:     /new
    defaults: { _controller: "AppBundle:CategoryAbstract:new" }
    methods:  [GET, POST]

cms_categories_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:CategoryAbstract:edit" }
    methods:  [GET, POST]

cms_categories_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:CategoryAbstract:delete" }
    methods:  DELETE
