contracts_index:
    path:     /
    defaults: { _controller: "AppBundle:Contract:index" }
    methods:  GET

contracts_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Contract:show" }
    methods:  GET

contracts_new:
    path:     /new
    defaults: { _controller: "AppBundle:Contract:new" }
    methods:  [GET, POST]

contracts_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Contract:edit" }
    methods:  [GET, POST]

contracts_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Contract:delete" }
    methods:  DELETE