insurerbasetariff_index:
    path:     /
    defaults: { _controller: "AppBundle:InsurerBaseTariff:index" }
    methods:  GET

insurerbasetariff_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:InsurerBaseTariff:show" }
    methods:  GET

insurerbasetariff_new:
    path:     /new
    defaults: { _controller: "AppBundle:InsurerBaseTariff:new" }
    methods:  [GET, POST]

insurerbasetariff_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:InsurerBaseTariff:edit" }
    methods:  [GET, POST]

insurerbasetariff_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:InsurerBaseTariff:delete" }
    methods:  DELETE
