insurers_index:
    path:     /
    defaults: { _controller: "AppBundle:Insurer:index" }
    methods:  GET

insurers_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Insurer:show" }
    methods:  GET

insurers_new:
    path:     /new
    defaults: { _controller: "AppBundle:Insurer:new" }
    methods:  [GET, POST]

insurers_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Insurer:edit" }
    methods:  [GET, POST]

insurers_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Insurer:delete" }
    methods:  DELETE
