sonata_user:
    security_acl: true
    manager_type: orm # can be orm or mongodb
    
doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    SonataUserBundle: ~
                    ApplicationSonataUserBundle: ~                    
    dbal:
        types:
            json: Sonata\Doctrine\Types\JsonType