<?php

namespace AppBundle\Repository\Car;

use Doctrine\ORM\EntityRepository;
/**
 * CategoryTariffRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryTariffRepository extends EntityRepository
{    
}
