<?php

namespace AppBundle\Repository\Car;

use Doctrine\ORM\EntityRepository;

/**
 * EngineCapacityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EngineCapacityRepository extends EntityRepository
{
}
