<?php

namespace AppBundle\Repository\Car;

use Doctrine\ORM\EntityRepository;
use AppBundle\Entity\Insurer;
use AppBundle\Entity\Car\Region;

/**
 * CarRegionTariffRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegionTariffRepository extends EntityRepository
{
    
    public function getRegionTariffByInsurerAndRegion(Insurer $insurer, Region $region){
        
       return $this->createQueryBuilder('r')
            ->andWhere('r.insurer = :insurer')
            ->andWhere('r.region = :region')
            ->setParameters(array(
                'insurer' => $insurer,
                'region' => $region
            ))
            ->getQuery()
            ->getOneOrNullResult();
    }
}
