<?php

namespace AppBundle\Repository\Car;

use Doctrine\ORM\EntityRepository;

/**
 * RegistrationNumberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegistrationNumberRepository extends EntityRepository
{
}
