<?php

namespace AppBundle\Repository\Car;

use Doctrine\ORM\EntityRepository;

/**
 * RightDirectionTariffRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RightDirectionTariffRepository extends EntityRepository
{
    

}
