<?php

namespace AppBundle\Repository\Driver;

use Doctrine\ORM\EntityRepository;

/**
 * DriverAccidentTariffRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccidentTariffRepository extends EntityRepository
{
}
