<?php

namespace AppBundle\Repository\Driver;

use Doctrine\ORM\EntityRepository;

/**
 * ExperienceTariffRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExperienceTariffRepository extends EntityRepository
{
}
